### ISSUE TITLE
collector/Database.cpp change breaks room temperature

### ISSUE THREAD

**Issue by ThetaGamma** [maniac103/ems-collector#17]
Betrifft collector/Database.cpp
hab einen Kommentar zu dem bug in Zeile 342 hinzugefügt. Hier ist seit März fest HK2 eincodiert, das müsste wahrscheinlich auch auf mehrere HKs aufgebohrt werden.
Cheers
TG

**Comment by maniac103** [comment]
Das ist kein Bug, zumindest nicht per se. Das ist einfach Konfigurationssache. Der richtige Fix dafür wäre IMHO, die in die DB geschriebenen Sensoren konfigurierbar zu machen.

**Comment by ThetaGamma** [comment]
OK, aber selbst wenn ich manuell in diesen beiden Zeilen HK1 eintrage, wird der Wert nicht in die DB geschrieben. Die RC ist auf HK1 eingestellt. der collectord liefert mir dann "DATA: HK1-Raum-Isttemperatur = 21 °C". Also evtl doch ein Bug?
Wegen der Konfigurierbarkeit: Könnte man prinzipiell solche "Variablen" im Makefile hinterlegen?

**Comment by maniac103** [comment]
Das ist nun endlich gefixt: https://github.com/maniac103/ems-collector/commit/e68c51817dd7b2ba1ebbd9d2a61b0e5505e070b6
