### ISSUE TITLE
Avoid use a leading forward slash

### ISSUE THREAD

**Issue by mafe** [maniac103/ems-collector#21]
I am using mqttwarn for gathering data and the leading slash is not parsed and
so is the whole subscription.

As mentioned in this article <https://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices>
it is not good practice using this slash.

`
Don’t use a leading forward slash
It is allowed to use a leading forward slash in MQTT, for example /myhome/groundfloor/livingroom. But that introduces a unnecessary topic level with a zero character at the front. That should be avoided, because it doesn’t provide any benefit and often leads to confusion.
`

Relevant code snippet in MqttAdapter.cpp:

```
MqttAdapter::handleValue(const EmsValue& value)
{
    if (!m_connected) {
	return;
    }

    std::string type = ValueApi::getTypeName(value.getType());
    std::string subtype = ValueApi::getSubTypeName(value.getSubType());

    std::string topic = "/ems/sensor/";
```

So, can you remove this leading slash?

**Comment by mafe** [comment]
bump

`
--- a/collector/MqttAdapter.cpp
+++ b/collector/MqttAdapter.cpp
@@ -51,7 +51,7 @@ MqttAdapter::handleValue(const EmsValue& value)
     std::string type = ValueApi::getTypeName(value.getType());
     std::string subtype = ValueApi::getSubTypeName(value.getSubType());
 
-    std::string topic = "/ems/sensor/";
+    std::string topic = "ems/sensor/";
     if (!subtype.empty()) {
        topic += subtype + "/";
     }
`

**Comment by maniac103** [comment]
Sorry, this fell off my radar :-/
Yes, I can remove it, but I'm a bit reluctant to do it because of backwards compatibility. 
I don't yet fully understand the problem - is using the leading slash just bad practice / not recommended or is it really a problem / forbidden, as your initial sentence implies?

**Comment by mafe** [comment]
No problem.
As I quoted above, the problem is the slash introduces an unnecessary topic level with a zero character at the front and does not work for me with 'mqttwarn'.
I am currently working on archlinux AUR packages and stumpled upon this again.

**Comment by maniac103** [comment]
OK, but the fact it's allowed (even if frowned upon), but doesn't work with mqttwarn implies there's a bug there as well that may be worth being reported?

I'm currently thinking about whether I want the topic prefix user configurable or whether I just omit the leading slash. The former seems more flexible, especially if collector users are now going to use pre-made packages ;-)

**Comment by mafe** [comment]
The user-defined prefix would fit perfectly from my point of view.
But, I will also check mqttwarn for proper handling on subscribing topics with/without slashes.
