### ISSUE TITLE
Compilation fails with Mqtt-option enabled (Debian 9 & libboost1.62-all-dev)

### ISSUE THREAD

**Issue by NoNeedForAName123** [maniac103/ems-collector#22]
Hi i'm trying to compile ems-collector on a Debian 9 system. Without MQTT it compiles well, but with i got an error...

[docker_build_ems-collector.txt](https://github.com/maniac103/ems-collector/files/2729563/docker_build_ems-collector.txt)
[output.txt](https://github.com/maniac103/ems-collector/files/2729566/output.txt)

 I have tried both libs from redboltz
  https://github.com/redboltz/mqtt_cpp.git
  git://github.com/redboltz/mqtt_client_cpp
But both with same errors.

Any ideas how to solve this :-(

**Comment by maniac103** [comment]
What compiler do you use? Looks like the mqtt lib now finally really requires C++14.

**Comment by maniac103** [comment]
Oh, yeah, that's #20 ... I totally forgot about that one :-(

**Comment by NoNeedForAName123** [comment]
Hi, I changed the on line from #20 and with the c++14 compiler it works now.
here the changes I have made:

/ems-collector/collector/Makefile: line 2 modify std=...
CFLAGS = -Wall -c -O2 -std=c++1**4** -DHAVE_DAEMONIZE

/ems-collector/collector/MqttAdapter.h: replace Line 69 with 
std::shared_ptr<mqtt::client<mqtt::tcp_endpoint<boost::asio::ip::tcp::socket, boost::asio::io_service::strand> > > m_client;

Thx!
